---

- name: Check ports are listening
  community.general.listen_ports_facts:

- name: TCP whitelist violation
  ansible.builtin.debug:
    msg: TCP port {{ item.port }} by pid {{ item.pid }} violates the whitelist
  vars:
    tcp_listen_violations: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', tcp_whitelist) | list }}"
    tcp_whitelist:
      - 22
      - 25
  loop: "{{ tcp_listen_violations }}"

- name: Check ports are reacheble
  ansible.builtin.wait_for:
    host: "{{ item.h }}"
    port: "{{ item.p }}"
    timeout: 10
  when:
    - ports is defined
  loop: "{{ ports |flatten(levels=1) }}"
