---

- name: Check config
  ansible.builtin.template:
    src: agent.config.j2
    # dest: "{{ nagios_config_dir }}/ansible/{{ ansible_hostname }}.cfg"
    dest: "/tmp/{{ ansible_hostname }}.cfg"
    owner: nagios
    group: nagios
    mode: "0755"
    backup: true
  register: create_config
  delegate_to: nagios
