---

- hosts: all
  vars:
    list_of_groups: "{{ groups }}"
    list_of_hosts: "{{ list_of_groups|map('extract', groups)|flatten|unique }}"
  tasks:
    - debug:
        var: list_of_groups
      run_once: true

    - debug:
        var: list_of_hosts
      run_once: true

    - name: Create list of hosts
      ansible.builtin.template:
        src: agent.cfg.j2
        dest: /tmp/{{ item }}.cfg
      loop: "{{ list_of_groups }}"