---

- name: Debug hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Get stated hosts
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - updated_hosts
        - dummy
