---

- hosts: all
  vars:
    updated_hosts:
      - name: "test"
        ip: "10.2.2.3"
  tasks:
    - name: Create dictionary with hosts names and ip in a fact
      ansible.builtin.set_fact:
        updated_hosts: "{{ updated_hosts + [{'name' : ansible_hostname, 'ip': ansible_default_ipv4.address}] }}"

    - name: Show list
      ansible.builtin.debug: 
        msg: "{{ updated_hosts }}"
