---

- name: Create list of servers to configure Nagios Agent
  hosts: all
  vars:
    updated_hosts: []
    stated_hosts: []
  tasks:
    - name: Create dictionary with hosts names and ip in a fact
      ansible.builtin.set_fact:
        updated_hosts: "{{ updated_hosts + [{'name': ansible_hostname, 'ip': ansible_default_ipv4.address}] }}"

    - name: Create list with stat
      ansible.builtin.set_stats:
        aggregate: true
        per_host: true
        data:
          stated_hosts: "hola" 
